language: cpp

env:
  global:
    - CXX_FLAGS="-Wall -pedantic -Werror"

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: clang
      sudo: true
      addons:
        apt:
          update: true
          sources: ['ubuntu-toolchain-r-test']
          packages:
          - cmake-data
          - cmake
          - libgtest-dev

before_install:
  - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}
  - export CTEST_OUTPUT_ON_FAILURE=1
  - export GTEST_COLOR=1

install:
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo cmake --build
  - sudo cp *.a /usr/lib/

script:
  - mkdir -p build
  - cmake -Bbuild -H.
  - make -C build
  - make -C build test
